language: python
install:
  - pip install ansible-lint
  - ansible-lint --version
script:
  - ansible-lint create-selfsigned-certs.yml
  - ansible-lint provision-vagrant.yml
  - ansible-list provision-swarm.yml