- hosts: local
  connection: local
 
  vars: 
    path: 'certs'

  tasks:
    - name: create CA key
      openssl_privatekey:
        path: "{{ path }}/CA_key.pem"
      register: ca_key

    - name: create the CA CSR
      openssl_csr:
        path: "{{ path }}/CA.csr"
        privatekey_path: "{{ ca_key.filename }}"
        common_name: "my-ca"
      register: ca_csr

    - name: sign the CA CSR
      openssl_certificate:
        path: "{{ path }}/CA.crt"
        csr_path: "{{ ca_csr.filename }}"
        privatekey_path: "{{ ca_key.filename }}"
        provider: selfsigned
      register: ca_crt

    - name: create host CSR signing key
      openssl_privatekey:
        path: "{{ path }}/docker.pem"
      register: docker_key

    - name: create the CSR for the docker server
      openssl_csr:
        path: "{{ path }}/docker.csr"
        privatekey_path: "{{ docker_key.filename }}"
        common_name: test.com
        subject_alt_name: 'DNS:my.test.com'
      register: docker_csr      

    - name: sign the CSR for the docker server
      openssl_certificate:
        path: "{{ path }}/docker.crt"
        csr_path: "{{ docker_csr.filename }}"
        provider: ownca
        ownca_path: "{{ ca_crt.filename }}"
        ownca_privatekey_path: "{{ ca_key.filename }}"
      register: docker_crt