---
- hosts: local
  connection: local
  become: true
  become_user: root

  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}-19.3.13"
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: false
    certdir: "./certs"

  roles:
    #upd vagrant img
    - provision_vagrant
    #install docker
    - geerlingguy.docker
    #secure docker api
    - { role: secure_docker, rootca_certificate: "{{ lookup('file', '{{ certdir }}/CA.crt') }}", server_certificate: "{{ lookup('file', '{{ certdir }}/docker.crt') }}", server_privatekey: "{{ lookup('file',  '{{ certdir }}/docker.pem') }}" }